### ISSUE TITLE
Create an enumeration of metric prefixes.

### ISSUE THREAD

**Issue by alexandrehsaad** [alexandrehsaad/swift-extensions#111]
# Subtasks

- [x] Conform to Comparable. 
- [x] Conform to Equatable.
- [x] Conform to RawRepresentable.
