### ISSUE TITLE
Stacks

### ISSUE THREAD

**Issue by alexandrehsaad** [alexandrehsaad/swift-extensions#120]
# User Story

As a software engineer, I want an object representing a queue, so I can get things out in the reverse order that I put them in.

# Acceptance Criteria

- Ability to pop the last element in the queue.
- Ability to push element at the back of the queue. 
- Ability to be encoded and decoded.
- Ability to be expressed by an array literal.

# Tasks

- [x] Create an object representing a queue.
- [x] Conform to CustomDebugStringConvertible.
- [x] Conform to CustomStringConvertible.
- [x] Conform to Decodable.
- [x] Conform to Encodable.
- [x] Conform to Equatable.
- [x] Conform to ExpressibleByArrayLiteral.
- [x] Conform to Hashable.
