### ISSUE TITLE
File System Nodes

### ISSUE THREAD

**Issue by alexandrehsaad** [alexandrehsaad/swift-extensions#124]
# User Story

As a software engineer, I want a tree collection, so I can imitate a structure of files and subfolders within folders.

# Acceptance Criteria
 
- Ability to be iterated as a sequence.
- Ability to access its files and subfolders.
- Ability to remove or move its files and subfolders. 
- Ability to be encoded and decoded.
- Ability to initialize it as a result builder.

# Tasks

- [x] Create an object representing a node.
- [x] Conform to CustomStringConvertible.
- [ ] Conform to Decodable.
- [ ] Conform to Encodable.
- [x] Conform to Equatable.
- [x] Conform to Hashable.
- [x] Conform to Sequence.
- [x] Create a node iterator.
- [x] Create a node result builder.
